version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=False
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/attachments:/app/static/attachments
      - ./database:/app/database
    restart: unless-stopped
